In [1]:
import torch

In [2]:
a = torch.rand(6)
b = torch.rand(6)
c = torch.rand(6)
[a, b, c]

[tensor([0.2859, 0.2315, 0.6125, 0.0917, 0.7203, 0.0546]),
 tensor([0.2401, 0.0420, 0.1979, 0.5013, 0.8952, 0.0941]),
 tensor([0.9257, 0.1764, 0.6721, 0.2044, 0.1741, 0.3446])]

In [3]:
torch.save([a, b, c],"model/tensor_abc")

In [4]:
torch.load("model/tensor_abc")

[tensor([0.2859, 0.2315, 0.6125, 0.0917, 0.7203, 0.0546]),
 tensor([0.2401, 0.0420, 0.1979, 0.5013, 0.8952, 0.0941]),
 tensor([0.9257, 0.1764, 0.6721, 0.2044, 0.1741, 0.3446])]

In [5]:
tensor_dict = {'a':a, 'b':b, 'c':c}

In [6]:
torch.save(tensor_dict,"model/tensor_dict_abc")

In [7]:
torch.load("model/tensor_dict_abc")

{'a': tensor([0.2859, 0.2315, 0.6125, 0.0917, 0.7203, 0.0546]),
 'b': tensor([0.2401, 0.0420, 0.1979, 0.5013, 0.8952, 0.0941]),
 'c': tensor([0.9257, 0.1764, 0.6721, 0.2044, 0.1741, 0.3446])}

In [8]:
import torch.nn as nn
import torch.optim as optim

### method 1

In [9]:
class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, num_classes)
        
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.relu(out)
        out = self.fc3(out)
        return out

input_size = 28*28
hidden_size = 512
num_classes = 10
model = MLP(input_size, hidden_size, num_classes)

In [10]:
torch.save(model.state_dict(),"model/mlp_state_dict.pth")

In [11]:
mlp_state_dict = torch.load("model/mlp_state_dict.pth")
model = MLP(input_size,hidden_size,num_classes)
model.load_state_dict(mlp_state_dict)

<All keys matched successfully>

### method 2

In [12]:
torch.save(model,"model/mlp_model.pth")
mlp_load = torch.load("model/mlp_model.pth")

Cons: Relative paths: If the working directory changes, the relative path "model/mlp_model.pth" might not point to the correct location, leading to FileNotFoundError when loading.

### method 3

In [13]:
epoch = 10
learning_rate = 0.001
optimizer = optim.Adam(model.parameters(),lr=learning_rate)
loss = 0.01
PATH = "model/model_checkpoint.pth"

In [14]:
torch.save({
    'epoch': epoch,
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
    'loss': loss,
}, PATH)

In [15]:
# load
model = MLP(input_size,hidden_size,num_classes)
optimizer = optim.Adam(model.parameters(),lr=learning_rate)

checkpoint = torch.load(PATH)
model.load_state_dict(checkpoint['model_state_dict'])
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
epoch = checkpoint['epoch']
loss = checkpoint['loss']

model.eval()

MLP(
  (fc1): Linear(in_features=784, out_features=512, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=512, out_features=512, bias=True)
  (fc3): Linear(in_features=512, out_features=10, bias=True)
)