In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
x = iris.data
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
y[y!=0] = 1

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=666)

In [6]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(x_train,y_train)
y_predict = log_reg.predict(x_test)

### 手动实现

In [7]:
TN = np.sum((y_predict==0)&(y_test==0))
TN

10

In [8]:
FP = np.sum((y_predict==1)&(y_test==0))
FP

0

In [9]:
FN = np.sum((y_predict==0)&(y_test==1))
FN

0

In [10]:
TP = np.sum((y_predict==1)&(y_test==1))
FN

0

In [11]:
confusion_matrix = np.array([
    [TN, FP],
    [FN, TP]
])
confusion_matrix

array([[10,  0],
       [ 0, 28]])

In [12]:
precision = TP/(FP+TP)
precision    # 精准率

1.0

In [13]:
recall = TP/(FN+TP)
recall    # 漏检率

1.0

In [14]:
f1_score = 2*precision*recall/(precision+recall)
f1_score

1.0

In [15]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_predict)

array([[10,  0],
       [ 0, 28]], dtype=int64)

In [16]:
from sklearn.metrics import precision_score
precision_score(y_test, y_predict)

1.0

In [17]:
from sklearn.metrics import recall_score
recall_score(y_test, y_predict)

1.0

In [18]:
from sklearn.metrics import f1_score
f1_score(y_test, y_predict)

1.0