In [4]:
import numpy as np
state = np.array(['认真复习', '简单复习', '没有复习'])
grade = np.array(['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-'])
n_state = len(state)
m_grade = len(grade)
pi = np.ones(n_state)/n_state
t = np.array([
    [0.4, 0.3, 0.3],
    [0.3, 0.4, 0.3],
    [0.3, 0.3, 0.4]
])
e = np.zeros([3, 9])
e[0, :9]=1/9
e[1, 3:9]=1/6
e[2, 5:9]=1/4

In [5]:
print("初始概率矩阵：\n", pi)
print("转移矩阵：\n", t)
print("发射矩阵：\n", e)

初始概率矩阵：
 [0.33333333 0.33333333 0.33333333]
转移矩阵：
 [[0.4 0.3 0.3]
 [0.3 0.4 0.3]
 [0.3 0.3 0.4]]
发射矩阵：
 [[0.11111111 0.11111111 0.11111111 0.11111111 0.11111111 0.11111111
  0.11111111 0.11111111 0.11111111]
 [0.         0.         0.         0.16666667 0.16666667 0.16666667
  0.16666667 0.16666667 0.16666667]
 [0.         0.         0.         0.         0.         0.25
  0.25       0.25       0.25      ]]


In [6]:
pip install hmmlearn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.3/161.3 kB 1.7 MB/s eta 0:00:00 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [7]:
from hmmlearn.hmm import CategoricalHMM
hmm = CategoricalHMM(n_state)

In [8]:
hmm.startprob_ = pi
hmm.transmat_ = t
hmm.emissionprob_ = e
hmm.n_features = 9

In [10]:
datas = np.array([0, 4, 2, 6, 1])
datas = np.expand_dims(datas, axis=1)
states = hmm.predict(datas)

In [11]:
states

array([0, 0, 0, 2, 0])

In [13]:
prob = hmm.score(datas)
prob

-14.003674820375014

In [14]:
print(np.exp(prob))

8.284786081615825e-07


In [15]:
data, states = hmm.sample(10000)

In [19]:
t_2 = np.zeros((3,3))
for i in range(3):
    current = np.where(states == i)[0]
    next_index = current+1
    next_index = next_index[:-1]
    
    tmp = states[next_index]
    for j in range(3):
        t_2[i][j] = np.where(tmp==j)[0].shape[0]/np.shape(tmp)[0]
print(t_2)

[[0.39280268 0.30802074 0.29917658]
 [0.29535736 0.39340257 0.31124007]
 [0.29732869 0.28368177 0.41898955]]
