In [26]:
import numpy as np

In [4]:
%%writefile test.py
def test(name):
    print(name)

Writing test.py


In [5]:
 %run test.py

In [16]:
test("Hello World")

Hello World


%测一行,%%测全部。timeit测很多次，time测一次。

In [12]:
%timeit data = [x * x for x in range(1000)]  

60.5 µs ± 5.35 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [14]:
%%timeit 
import time
time.sleep(0.5)

501 ms ± 250 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [18]:
%whos

Variable   Type        Data/Info
--------------------------------
test       function    <function test at 0x00000216B3851DA0>


In [36]:
%%timeit
x = [i for i in range(100000)]
sum_x=0
for i in x:
    sum_x+=i**2
sum_x

11.7 ms ± 374 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [35]:
%%timeit
x = np.arange(100000)
sum_x = np.sum(x**2)
sum_x

153 µs ± 1.04 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [40]:
X = np.linspace(10,40,4).reshape(2,2)

In [41]:
X

array([[10., 20.],
       [30., 40.]])

In [42]:
X.T

array([[10., 30.],
       [20., 40.]])

In [43]:
X = np.linalg.inv(X)

In [44]:
X

array([[-0.2 ,  0.1 ],
       [ 0.15, -0.05]])

In [45]:
np.linalg.det(X)

-0.005000000000000002